#单个的zookeeper配置
dubbo:
  protocol:
    name: dubbo
    port: 18889
  registry:
    address: zookeeper://localhost:2181
#  scan: org.lszjaf.dagger.controller
  application:
    name: luush-consumer


server:
  port: 10501
spring:
  application:
    name: service-dubbo-consumer