#zookeeper集群配置
dubbo:
  protocol:
    name: dubbo
    port: 18889
  registry:
    address: zookeeper://localhost:2181?backup=localhost:2182
#  scan: org.lszjaf.dagger.controller
  application:
    name: luush-consumer
#  consumer:
#    group: test1
server:
  port: 10501
spring:
  application:
    name: service-dubbo-consumer