#zookeeper集群有关配置
dubbo:
  protocol:
    name: dubbo
    port: 18889
#  registry:
#    address: zookeeper://localhost:2181
  scan: org.lszjaf.dagger.servicedubboprovider.impl
  application:
    name: luush-consumer
    registries[0]:
      address: zookeeper://localhost:2181
    registries[1]:
      address: zookeeper://localhost:2182
#  provider:
#    group: test1
server:
  port: 10500
spring:
  application:
    name: service-dubbo-provider